/* Generated by gen_dispatch_header.sh */
#if defined(_WIN32)
#	if defined(_M_IX86)
#		if defined(_MSC_VER) && _MSC_VER >= 1800 && _MSC_VER < 1900
#			include <my_config-win-x86-vc120.h>
#		elif defined(_MSC_VER) && _MSC_VER >= 1900 && _MSC_VER < 2000
#			include <my_config-win-x86-vc140.h>
#		else
#			error "Unsupported configuration"
#		endif
#	elif defined(_M_X64)
#		if defined(_MSC_VER) && _MSC_VER >= 1800 && _MSC_VER < 1900
#			include <my_config-win-x86_64-vc120.h>
#		elif defined(_MSC_VER) && _MSC_VER >= 1900 && _MSC_VER < 2000
#			include <my_config-win-x86_64-vc140.h>
#		else
#			error "Unsupported configuration"
#		endif
#	else
#		error "Unsupported configuration"
#	endif
#elif defined (__linux__)
#	if defined(__i386)
#		error "Unsupported configuration"
#	elif defined(__amd64)
#		error "Unsupported configuration"
#	else
#		error "Unsupported configuration"
#	endif
#else
#	error "Unknown platform"
#endif
