/* 
// Copyright 2015 Intel Corporation All Rights Reserved.
// 
// The source code, information and material ("Material") contained herein is
// owned by Intel Corporation or its suppliers or licensors, and title
// to such Material remains with Intel Corporation or its suppliers or
// licensors. The Material contains proprietary information of Intel
// or its suppliers and licensors. The Material is protected by worldwide
// copyright laws and treaty provisions. No part of the Material may be used,
// copied, reproduced, modified, published, uploaded, posted, transmitted,
// distributed or disclosed in any way without Intel's prior express written
// permission. No license under any patent, copyright or other intellectual
// property rights in the Material is granted to or conferred upon you,
// either expressly, by implication, inducement, estoppel or otherwise.
// Any license under such intellectual property rights must be express and
// approved by Intel in writing.
// 
// Unless otherwise agreed by Intel in writing,
// you may not remove or alter this notice or any other notice embedded in
// Materials by Intel or Intel's suppliers or licensors in any way.
// 
*/

#if !defined( __IPPCV_LEGACY_90_REDEFS_H__ )
#define __IPPCV_LEGACY_90_REDEFS_H__

#if !defined( __NO_IPPCV_LEGACY_90_REDEF )

#define ippiAddProduct_8s32f_C1IMR legacy90ippiAddProduct_8s32f_C1IMR
#define ippiAddProduct_8s32f_C1IR legacy90ippiAddProduct_8s32f_C1IR
#define ippiAddSquare_8s32f_C1IMR legacy90ippiAddSquare_8s32f_C1IMR
#define ippiAddSquare_8s32f_C1IR legacy90ippiAddSquare_8s32f_C1IR
#define ippiAddWeighted_8s32f_C1IMR legacy90ippiAddWeighted_8s32f_C1IMR
#define ippiAddWeighted_8s32f_C1IR legacy90ippiAddWeighted_8s32f_C1IR
#define ippiAdd_8s32f_C1IMR legacy90ippiAdd_8s32f_C1IMR
#define ippiAdd_8s32f_C1IR legacy90ippiAdd_8s32f_C1IR
#define ippiDilateBorderReplicate_32f_C1R legacy90ippiDilateBorderReplicate_32f_C1R
#define ippiDilateBorderReplicate_32f_C3R legacy90ippiDilateBorderReplicate_32f_C3R
#define ippiDilateBorderReplicate_32f_C4R legacy90ippiDilateBorderReplicate_32f_C4R
#define ippiDilateBorderReplicate_8u_C1R legacy90ippiDilateBorderReplicate_8u_C1R
#define ippiDilateBorderReplicate_8u_C3R legacy90ippiDilateBorderReplicate_8u_C3R
#define ippiDilateBorderReplicate_8u_C4R legacy90ippiDilateBorderReplicate_8u_C4R
#define ippiErodeBorderReplicate_32f_C1R legacy90ippiErodeBorderReplicate_32f_C1R
#define ippiErodeBorderReplicate_32f_C3R legacy90ippiErodeBorderReplicate_32f_C3R
#define ippiErodeBorderReplicate_32f_C4R legacy90ippiErodeBorderReplicate_32f_C4R
#define ippiErodeBorderReplicate_8u_C1R legacy90ippiErodeBorderReplicate_8u_C1R
#define ippiErodeBorderReplicate_8u_C3R legacy90ippiErodeBorderReplicate_8u_C3R
#define ippiErodeBorderReplicate_8u_C4R legacy90ippiErodeBorderReplicate_8u_C4R
#define ippiFilterGaussBorder_32f_C1R legacy90ippiFilterGaussBorder_32f_C1R
#define ippiFilterGaussGetBufferSize_32f_C1R legacy90ippiFilterGaussGetBufferSize_32f_C1R
#define ippiFilterLaplacianBorder_8u8s_C1R legacy90ippiFilterLaplacianBorder_8u8s_C1R
#define ippiFilterLaplacianGetBufferSize_8u8s_C1R legacy90ippiFilterLaplacianGetBufferSize_8u8s_C1R
#define ippiFilterMaxBorderReplicate_32f_C1R legacy90ippiFilterMaxBorderReplicate_32f_C1R
#define ippiFilterMaxBorderReplicate_32f_C3R legacy90ippiFilterMaxBorderReplicate_32f_C3R
#define ippiFilterMaxBorderReplicate_32f_C4R legacy90ippiFilterMaxBorderReplicate_32f_C4R
#define ippiFilterMaxBorderReplicate_8u_C1R legacy90ippiFilterMaxBorderReplicate_8u_C1R
#define ippiFilterMaxBorderReplicate_8u_C3R legacy90ippiFilterMaxBorderReplicate_8u_C3R
#define ippiFilterMaxBorderReplicate_8u_C4R legacy90ippiFilterMaxBorderReplicate_8u_C4R
#define ippiFilterMaxGetBufferSize_32f_C1R legacy90ippiFilterMaxGetBufferSize_32f_C1R
#define ippiFilterMaxGetBufferSize_32f_C3R legacy90ippiFilterMaxGetBufferSize_32f_C3R
#define ippiFilterMaxGetBufferSize_32f_C4R legacy90ippiFilterMaxGetBufferSize_32f_C4R
#define ippiFilterMaxGetBufferSize_8u_C1R legacy90ippiFilterMaxGetBufferSize_8u_C1R
#define ippiFilterMaxGetBufferSize_8u_C3R legacy90ippiFilterMaxGetBufferSize_8u_C3R
#define ippiFilterMaxGetBufferSize_8u_C4R legacy90ippiFilterMaxGetBufferSize_8u_C4R
#define ippiFilterMinBorderReplicate_32f_C1R legacy90ippiFilterMinBorderReplicate_32f_C1R
#define ippiFilterMinBorderReplicate_32f_C3R legacy90ippiFilterMinBorderReplicate_32f_C3R
#define ippiFilterMinBorderReplicate_32f_C4R legacy90ippiFilterMinBorderReplicate_32f_C4R
#define ippiFilterMinBorderReplicate_8u_C1R legacy90ippiFilterMinBorderReplicate_8u_C1R
#define ippiFilterMinBorderReplicate_8u_C3R legacy90ippiFilterMinBorderReplicate_8u_C3R
#define ippiFilterMinBorderReplicate_8u_C4R legacy90ippiFilterMinBorderReplicate_8u_C4R
#define ippiFilterMinGetBufferSize_32f_C1R legacy90ippiFilterMinGetBufferSize_32f_C1R
#define ippiFilterMinGetBufferSize_32f_C3R legacy90ippiFilterMinGetBufferSize_32f_C3R
#define ippiFilterMinGetBufferSize_32f_C4R legacy90ippiFilterMinGetBufferSize_32f_C4R
#define ippiFilterMinGetBufferSize_8u_C1R legacy90ippiFilterMinGetBufferSize_8u_C1R
#define ippiFilterMinGetBufferSize_8u_C3R legacy90ippiFilterMinGetBufferSize_8u_C3R
#define ippiFilterMinGetBufferSize_8u_C4R legacy90ippiFilterMinGetBufferSize_8u_C4R
#define ippiFilterScharrHorizBorder_32f_C1R legacy90ippiFilterScharrHorizBorder_32f_C1R
#define ippiFilterScharrHorizBorder_8u16s_C1R legacy90ippiFilterScharrHorizBorder_8u16s_C1R
#define ippiFilterScharrHorizBorder_8u8s_C1R legacy90ippiFilterScharrHorizBorder_8u8s_C1R
#define ippiFilterScharrHorizGetBufferSize_32f_C1R legacy90ippiFilterScharrHorizGetBufferSize_32f_C1R
#define ippiFilterScharrHorizGetBufferSize_8u16s_C1R legacy90ippiFilterScharrHorizGetBufferSize_8u16s_C1R
#define ippiFilterScharrHorizGetBufferSize_8u8s_C1R legacy90ippiFilterScharrHorizGetBufferSize_8u8s_C1R
#define ippiFilterScharrVertBorder_32f_C1R legacy90ippiFilterScharrVertBorder_32f_C1R
#define ippiFilterScharrVertBorder_8u16s_C1R legacy90ippiFilterScharrVertBorder_8u16s_C1R
#define ippiFilterScharrVertBorder_8u8s_C1R legacy90ippiFilterScharrVertBorder_8u8s_C1R
#define ippiFilterScharrVertGetBufferSize_32f_C1R legacy90ippiFilterScharrVertGetBufferSize_32f_C1R
#define ippiFilterScharrVertGetBufferSize_8u16s_C1R legacy90ippiFilterScharrVertGetBufferSize_8u16s_C1R
#define ippiFilterScharrVertGetBufferSize_8u8s_C1R legacy90ippiFilterScharrVertGetBufferSize_8u8s_C1R
#define ippiFilterSobelCrossBorder_8u8s_C1R legacy90ippiFilterSobelCrossBorder_8u8s_C1R
#define ippiFilterSobelCrossGetBufferSize_8u8s_C1R legacy90ippiFilterSobelCrossGetBufferSize_8u8s_C1R
#define ippiFilterSobelHorizBorder_8u8s_C1R legacy90ippiFilterSobelHorizBorder_8u8s_C1R
#define ippiFilterSobelHorizGetBufferSize_8u8s_C1R legacy90ippiFilterSobelHorizGetBufferSize_8u8s_C1R
#define ippiFilterSobelHorizSecondBorder_8u8s_C1R legacy90ippiFilterSobelHorizSecondBorder_8u8s_C1R
#define ippiFilterSobelHorizSecondGetBufferSize_32f_C1R legacy90ippiFilterSobelHorizSecondGetBufferSize_32f_C1R
#define ippiFilterSobelHorizSecondGetBufferSize_8u16s_C1R legacy90ippiFilterSobelHorizSecondGetBufferSize_8u16s_C1R
#define ippiFilterSobelHorizSecondGetBufferSize_8u8s_C1R legacy90ippiFilterSobelHorizSecondGetBufferSize_8u8s_C1R
#define ippiFilterSobelNegVertBorder_8u8s_C1R legacy90ippiFilterSobelNegVertBorder_8u8s_C1R
#define ippiFilterSobelNegVertGetBufferSize_32f_C1R legacy90ippiFilterSobelNegVertGetBufferSize_32f_C1R
#define ippiFilterSobelNegVertGetBufferSize_8u16s_C1R legacy90ippiFilterSobelNegVertGetBufferSize_8u16s_C1R
#define ippiFilterSobelNegVertGetBufferSize_8u8s_C1R legacy90ippiFilterSobelNegVertGetBufferSize_8u8s_C1R
#define ippiFilterSobelVertBorder_8u8s_C1R legacy90ippiFilterSobelVertBorder_8u8s_C1R
#define ippiFilterSobelVertGetBufferSize_8u8s_C1R legacy90ippiFilterSobelVertGetBufferSize_8u8s_C1R
#define ippiFilterSobelVertSecondBorder_8u8s_C1R legacy90ippiFilterSobelVertSecondBorder_8u8s_C1R
#define ippiFilterSobelVertSecondGetBufferSize_32f_C1R legacy90ippiFilterSobelVertSecondGetBufferSize_32f_C1R
#define ippiFilterSobelVertSecondGetBufferSize_8u16s_C1R legacy90ippiFilterSobelVertSecondGetBufferSize_8u16s_C1R
#define ippiFilterSobelVertSecondGetBufferSize_8u8s_C1R legacy90ippiFilterSobelVertSecondGetBufferSize_8u8s_C1R
#define ippiForegroundGaussianFree_8u_C1R legacy90ippiForegroundGaussianFree_8u_C1R
#define ippiForegroundGaussianFree_8u_C3R legacy90ippiForegroundGaussianFree_8u_C3R
#define ippiForegroundGaussianInitAlloc_8u_C1R legacy90ippiForegroundGaussianInitAlloc_8u_C1R
#define ippiForegroundGaussianInitAlloc_8u_C3R legacy90ippiForegroundGaussianInitAlloc_8u_C3R
#define ippiForegroundGaussian_8u_C1R legacy90ippiForegroundGaussian_8u_C1R
#define ippiForegroundGaussian_8u_C3R legacy90ippiForegroundGaussian_8u_C3R
#define ippiForegroundHistogramFree_8u_C1R legacy90ippiForegroundHistogramFree_8u_C1R
#define ippiForegroundHistogramFree_8u_C3R legacy90ippiForegroundHistogramFree_8u_C3R
#define ippiForegroundHistogramInitAlloc_8u_C1R legacy90ippiForegroundHistogramInitAlloc_8u_C1R
#define ippiForegroundHistogramInitAlloc_8u_C3R legacy90ippiForegroundHistogramInitAlloc_8u_C3R
#define ippiForegroundHistogramUpdate_8u_C1R legacy90ippiForegroundHistogramUpdate_8u_C1R
#define ippiForegroundHistogramUpdate_8u_C3R legacy90ippiForegroundHistogramUpdate_8u_C3R
#define ippiForegroundHistogram_8u_C1R legacy90ippiForegroundHistogram_8u_C1R
#define ippiForegroundHistogram_8u_C3R legacy90ippiForegroundHistogram_8u_C3R
#define ippiMean_8s_C1MR legacy90ippiMean_8s_C1MR
#define ippiMean_8s_C3CMR legacy90ippiMean_8s_C3CMR
#define ippiMean_StdDev_8s_C1MR legacy90ippiMean_StdDev_8s_C1MR
#define ippiMean_StdDev_8s_C1R legacy90ippiMean_StdDev_8s_C1R
#define ippiMean_StdDev_8s_C3CMR legacy90ippiMean_StdDev_8s_C3CMR
#define ippiMean_StdDev_8s_C3CR legacy90ippiMean_StdDev_8s_C3CR
#define ippiMinMaxIndx_8s_C1MR legacy90ippiMinMaxIndx_8s_C1MR
#define ippiMinMaxIndx_8s_C1R legacy90ippiMinMaxIndx_8s_C1R
#define ippiMinMaxIndx_8s_C3CMR legacy90ippiMinMaxIndx_8s_C3CMR
#define ippiMinMaxIndx_8s_C3CR legacy90ippiMinMaxIndx_8s_C3CR
#define ippiMorphAdvFree legacy90ippiMorphAdvFree
#define ippiMorphAdvInitAlloc_32f_C1R legacy90ippiMorphAdvInitAlloc_32f_C1R
#define ippiMorphAdvInitAlloc_32f_C3R legacy90ippiMorphAdvInitAlloc_32f_C3R
#define ippiMorphAdvInitAlloc_32f_C4R legacy90ippiMorphAdvInitAlloc_32f_C4R
#define ippiMorphAdvInitAlloc_8u_C1R legacy90ippiMorphAdvInitAlloc_8u_C1R
#define ippiMorphAdvInitAlloc_8u_C3R legacy90ippiMorphAdvInitAlloc_8u_C3R
#define ippiMorphAdvInitAlloc_8u_C4R legacy90ippiMorphAdvInitAlloc_8u_C4R
#define ippiMorphGrayFree_32f_C1R legacy90ippiMorphGrayFree_32f_C1R
#define ippiMorphGrayFree_8u_C1R legacy90ippiMorphGrayFree_8u_C1R
#define ippiMorphGrayInitAlloc_32f_C1R legacy90ippiMorphGrayInitAlloc_32f_C1R
#define ippiMorphGrayInitAlloc_8u_C1R legacy90ippiMorphGrayInitAlloc_8u_C1R
#define ippiMorphReconstructGetBufferSize_16u_C1 legacy90ippiMorphReconstructGetBufferSize_16u_C1
#define ippiMorphReconstructGetBufferSize_32f_C1 legacy90ippiMorphReconstructGetBufferSize_32f_C1
#define ippiMorphReconstructGetBufferSize_64f_C1 legacy90ippiMorphReconstructGetBufferSize_64f_C1
#define ippiMorphReconstructGetBufferSize_8u_C1 legacy90ippiMorphReconstructGetBufferSize_8u_C1
#define ippiMorphologyFree legacy90ippiMorphologyFree
#define ippiMorphologyGetSize_32f_C1R legacy90ippiMorphologyGetSize_32f_C1R
#define ippiMorphologyGetSize_32f_C3R legacy90ippiMorphologyGetSize_32f_C3R
#define ippiMorphologyGetSize_32f_C4R legacy90ippiMorphologyGetSize_32f_C4R
#define ippiMorphologyGetSize_8u_C1R legacy90ippiMorphologyGetSize_8u_C1R
#define ippiMorphologyGetSize_8u_C3R legacy90ippiMorphologyGetSize_8u_C3R
#define ippiMorphologyGetSize_8u_C4R legacy90ippiMorphologyGetSize_8u_C4R
#define ippiMorphologyInitAlloc_32f_C1R legacy90ippiMorphologyInitAlloc_32f_C1R
#define ippiMorphologyInitAlloc_32f_C3R legacy90ippiMorphologyInitAlloc_32f_C3R
#define ippiMorphologyInitAlloc_32f_C4R legacy90ippiMorphologyInitAlloc_32f_C4R
#define ippiMorphologyInitAlloc_8u_C1R legacy90ippiMorphologyInitAlloc_8u_C1R
#define ippiMorphologyInitAlloc_8u_C3R legacy90ippiMorphologyInitAlloc_8u_C3R
#define ippiMorphologyInitAlloc_8u_C4R legacy90ippiMorphologyInitAlloc_8u_C4R
#define ippiMorphologyInit_32f_C1R legacy90ippiMorphologyInit_32f_C1R
#define ippiMorphologyInit_32f_C3R legacy90ippiMorphologyInit_32f_C3R
#define ippiMorphologyInit_32f_C4R legacy90ippiMorphologyInit_32f_C4R
#define ippiMorphologyInit_8u_C1R legacy90ippiMorphologyInit_8u_C1R
#define ippiMorphologyInit_8u_C3R legacy90ippiMorphologyInit_8u_C3R
#define ippiMorphologyInit_8u_C4R legacy90ippiMorphologyInit_8u_C4R
#define ippiNormDiff_Inf_8s_C1MR legacy90ippiNormDiff_Inf_8s_C1MR
#define ippiNormDiff_Inf_8s_C3CMR legacy90ippiNormDiff_Inf_8s_C3CMR
#define ippiNormDiff_L1_8s_C1MR legacy90ippiNormDiff_L1_8s_C1MR
#define ippiNormDiff_L1_8s_C3CMR legacy90ippiNormDiff_L1_8s_C3CMR
#define ippiNormDiff_L2_8s_C1MR legacy90ippiNormDiff_L2_8s_C1MR
#define ippiNormDiff_L2_8s_C3CMR legacy90ippiNormDiff_L2_8s_C3CMR
#define ippiNormRel_Inf_8s_C1MR legacy90ippiNormRel_Inf_8s_C1MR
#define ippiNormRel_Inf_8s_C3CMR legacy90ippiNormRel_Inf_8s_C3CMR
#define ippiNormRel_L1_8s_C1MR legacy90ippiNormRel_L1_8s_C1MR
#define ippiNormRel_L1_8s_C3CMR legacy90ippiNormRel_L1_8s_C3CMR
#define ippiNormRel_L2_8s_C1MR legacy90ippiNormRel_L2_8s_C1MR
#define ippiNormRel_L2_8s_C3CMR legacy90ippiNormRel_L2_8s_C3CMR
#define ippiNorm_Inf_8s_C1MR legacy90ippiNorm_Inf_8s_C1MR
#define ippiNorm_Inf_8s_C3CMR legacy90ippiNorm_Inf_8s_C3CMR
#define ippiNorm_L1_8s_C1MR legacy90ippiNorm_L1_8s_C1MR
#define ippiNorm_L1_8s_C3CMR legacy90ippiNorm_L1_8s_C3CMR
#define ippiNorm_L2_8s_C1MR legacy90ippiNorm_L2_8s_C1MR
#define ippiNorm_L2_8s_C3CMR legacy90ippiNorm_L2_8s_C3CMR
#define ippiPyrDownGetBufSize_Gauss5x5 legacy90ippiPyrDownGetBufSize_Gauss5x5
#define ippiPyrDown_Gauss5x5_32f_C1R legacy90ippiPyrDown_Gauss5x5_32f_C1R
#define ippiPyrDown_Gauss5x5_32f_C3R legacy90ippiPyrDown_Gauss5x5_32f_C3R
#define ippiPyrDown_Gauss5x5_8s_C1R legacy90ippiPyrDown_Gauss5x5_8s_C1R
#define ippiPyrDown_Gauss5x5_8s_C3R legacy90ippiPyrDown_Gauss5x5_8s_C3R
#define ippiPyrDown_Gauss5x5_8u_C1R legacy90ippiPyrDown_Gauss5x5_8u_C1R
#define ippiPyrDown_Gauss5x5_8u_C3R legacy90ippiPyrDown_Gauss5x5_8u_C3R
#define ippiPyrUpGetBufSize_Gauss5x5 legacy90ippiPyrUpGetBufSize_Gauss5x5
#define ippiPyrUp_Gauss5x5_32f_C1R legacy90ippiPyrUp_Gauss5x5_32f_C1R
#define ippiPyrUp_Gauss5x5_32f_C3R legacy90ippiPyrUp_Gauss5x5_32f_C3R
#define ippiPyrUp_Gauss5x5_8s_C1R legacy90ippiPyrUp_Gauss5x5_8s_C1R
#define ippiPyrUp_Gauss5x5_8s_C3R legacy90ippiPyrUp_Gauss5x5_8s_C3R
#define ippiPyrUp_Gauss5x5_8u_C1R legacy90ippiPyrUp_Gauss5x5_8u_C1R
#define ippiPyrUp_Gauss5x5_8u_C3R legacy90ippiPyrUp_Gauss5x5_8u_C3R
#define ippiSRHNCalcResidual_PSF2x2_16u32f_C1R legacy90ippiSRHNCalcResidual_PSF2x2_16u32f_C1R
#define ippiSRHNCalcResidual_PSF2x2_8u32f_C1R legacy90ippiSRHNCalcResidual_PSF2x2_8u32f_C1R
#define ippiSRHNCalcResidual_PSF3x3_16u32f_C1R legacy90ippiSRHNCalcResidual_PSF3x3_16u32f_C1R
#define ippiSRHNCalcResidual_PSF3x3_8u32f_C1R legacy90ippiSRHNCalcResidual_PSF3x3_8u32f_C1R
#define ippiSRHNFree_PSF2x2 legacy90ippiSRHNFree_PSF2x2
#define ippiSRHNFree_PSF3x3 legacy90ippiSRHNFree_PSF3x3
#define ippiSRHNInitAlloc_PSF2x2 legacy90ippiSRHNInitAlloc_PSF2x2
#define ippiSRHNInitAlloc_PSF3x3 legacy90ippiSRHNInitAlloc_PSF3x3
#define ippiSRHNUpdateGradient_PSF2x2_32f_C1R legacy90ippiSRHNUpdateGradient_PSF2x2_32f_C1R
#define ippiSRHNUpdateGradient_PSF3x3_32f_C1R legacy90ippiSRHNUpdateGradient_PSF3x3_32f_C1R
#define ippibFastArctan_32f legacy90ippibFastArctan_32f

#endif /* __NO_IPPCV_LEGACY_90_REDEF   */
#endif /* __IPPCV_LEGACY_90_REDEFS_H__ */

