
#ifndef VS_STREAMS_DEFINITIONS_H
#define VS_STREAMS_DEFINITIONS_H

#define   VS_STREAM_MAX_SIZE_FRAME   65500
#define   VS_STREAMS_MAX_SIZE_CONFERENCE_NAME   255
#define   VS_STREAMS_MAX_SIZE_PARTICIPANT_NAME   255
#define   VS_STREAMS_MAX_SIZE_SSLKEY   256

#define   VS_SR_STAT_N_TICKS   8
#define   VS_SR_STAT_N_MASK    (VS_SR_STAT_N_TICKS - 1)

#endif // VS_STREAMS_DEFINITIONS_H

