#ifndef VS_NETROUTERSELECT_H_HEADER_INCLUDED_BB8BABB4
#define VS_NETROUTERSELECT_H_HEADER_INCLUDED_BB8BABB4
#include "VS_NetRouter.h"

//##ModelId=44744D7F0200
class VS_NetRouterSelect : public VS_NetRouter
{
};



#endif /* VS_NETROUTERSELECT_H_HEADER_INCLUDED_BB8BABB4 */
