#ifndef VS_SLOTNETWORKLAYER_H_HEADER_INCLUDED_BB93A7CB
#define VS_SLOTNETWORKLAYER_H_HEADER_INCLUDED_BB93A7CB

//##ModelId=446C49F10104
class VS_SlotNetworkLayer
{
};



#endif /* VS_SLOTNETWORKLAYER_H_HEADER_INCLUDED_BB93A7CB */
