/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cciCommonV1_CONSTANTS_H
#define cciCommonV1_CONSTANTS_H

#include "cciCommonV1_types.h"

namespace sudis {

class cciCommonV1Constants {
 public:
  cciCommonV1Constants();

};

extern const cciCommonV1Constants g_cciCommonV1_constants;

} // namespace

#endif
