/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cciCommonV1_constants.h"

namespace sudis {

const cciCommonV1Constants g_cciCommonV1_constants;

cciCommonV1Constants::cciCommonV1Constants() {
}

} // namespace

