/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cciRoleCommonV1_CONSTANTS_H
#define cciRoleCommonV1_CONSTANTS_H

#include "cciRoleCommonV1_types.h"

namespace sudis {

class cciRoleCommonV1Constants {
 public:
  cciRoleCommonV1Constants();

};

extern const cciRoleCommonV1Constants g_cciRoleCommonV1_constants;

} // namespace

#endif
