/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cciUserListV2_constants.h"

namespace sudis {

const cciUserListV2Constants g_cciUserListV2_constants;

cciUserListV2Constants::cciUserListV2Constants() {
}

} // namespace

