/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cciUserRoleListV1_constants.h"

namespace sudis {

const cciUserRoleListV1Constants g_cciUserRoleListV1_constants;

cciUserRoleListV1Constants::cciUserRoleListV1Constants() {
}

} // namespace

