/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cciUserLoginV3_CONSTANTS_H
#define cciUserLoginV3_CONSTANTS_H

#include "cciUserLoginV3_types.h"



class cciUserLoginV3Constants {
 public:
  cciUserLoginV3Constants();

};

extern const cciUserLoginV3Constants g_cciUserLoginV3_constants;



#endif
