/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cciUserListV2_CONSTANTS_H
#define cciUserListV2_CONSTANTS_H

#include "cciUserListV2_types.h"

namespace sudis {

class cciUserListV2Constants {
 public:
  cciUserListV2Constants();

};

extern const cciUserListV2Constants g_cciUserListV2_constants;

} // namespace

#endif
