/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cciUserCommonV1_CONSTANTS_H
#define cciUserCommonV1_CONSTANTS_H

#include "cciUserCommonV1_types.h"

namespace sudis {

class cciUserCommonV1Constants {
 public:
  cciUserCommonV1Constants();

};

extern const cciUserCommonV1Constants g_cciUserCommonV1_constants;

} // namespace

#endif
