/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cciUserLoginV1_constants.h"

namespace sudis {

const cciUserLoginV1Constants g_cciUserLoginV1_constants;

cciUserLoginV1Constants::cciUserLoginV1Constants() {
}

} // namespace

