/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cciUserListV1_CONSTANTS_H
#define cciUserListV1_CONSTANTS_H

#include "cciUserListV1_types.h"

namespace sudis {

class cciUserListV1Constants {
 public:
  cciUserListV1Constants();

};

extern const cciUserListV1Constants g_cciUserListV1_constants;

} // namespace

#endif
