/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cciUserRoleListV1_types.h"

#include <algorithm>

namespace sudis {

const char* TCciUserRoleListV1Request::ascii_fingerprint = "2748901DF3E03B56075825ABF0FCFD25";
const uint8_t TCciUserRoleListV1Request::binary_fingerprint[16] = {0x27,0x48,0x90,0x1D,0xF3,0xE0,0x3B,0x56,0x07,0x58,0x25,0xAB,0xF0,0xFC,0xFD,0x25};

uint32_t TCciUserRoleListV1Request::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_userTokenId = false;
  bool isset_requestDateTime = false;
  bool isset_requestNonce = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->userTokenId);
          isset_userTokenId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->requestDateTime);
          isset_requestDateTime = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->requestNonce);
          isset_requestNonce = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->spCode);
          this->__isset.spCode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_userTokenId)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_requestDateTime)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_requestNonce)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TCciUserRoleListV1Request::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("TCciUserRoleListV1Request");

  xfer += oprot->writeFieldBegin("userTokenId", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->userTokenId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("requestDateTime", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->requestDateTime);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("requestNonce", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeBinary(this->requestNonce);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.spCode) {
    xfer += oprot->writeFieldBegin("spCode", ::apache::thrift::protocol::T_STRING, 4);
    xfer += oprot->writeString(this->spCode);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TCciUserRoleListV1Request &a, TCciUserRoleListV1Request &b) {
  using ::std::swap;
  swap(a.userTokenId, b.userTokenId);
  swap(a.requestDateTime, b.requestDateTime);
  swap(a.requestNonce, b.requestNonce);
  swap(a.spCode, b.spCode);
  swap(a.__isset, b.__isset);
}

const char* TCciUserRoleListV1Response::ascii_fingerprint = "932F2869C6C51F6F8871BF2C85008A08";
const uint8_t TCciUserRoleListV1Response::binary_fingerprint[16] = {0x93,0x2F,0x28,0x69,0xC6,0xC5,0x1F,0x6F,0x88,0x71,0xBF,0x2C,0x85,0x00,0x8A,0x08};

uint32_t TCciUserRoleListV1Response::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_responseDateTime = false;
  bool isset_responseNonce = false;
  bool isset_resultMessage = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->responseDateTime);
          isset_responseDateTime = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->responseNonce);
          isset_responseNonce = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->resultMessage.read(iprot);
          isset_resultMessage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->roleList.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->roleList.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += this->roleList[_i4].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.roleList = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_responseDateTime)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_responseNonce)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_resultMessage)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TCciUserRoleListV1Response::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("TCciUserRoleListV1Response");

  xfer += oprot->writeFieldBegin("responseDateTime", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->responseDateTime);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("responseNonce", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeBinary(this->responseNonce);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("resultMessage", ::apache::thrift::protocol::T_STRUCT, 3);
  xfer += this->resultMessage.write(oprot);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.roleList) {
    xfer += oprot->writeFieldBegin("roleList", ::apache::thrift::protocol::T_LIST, 4);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->roleList.size()));
      std::vector< ::sudis::TCciRoleV1> ::const_iterator _iter5;
      for (_iter5 = this->roleList.begin(); _iter5 != this->roleList.end(); ++_iter5)
      {
        xfer += (*_iter5).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TCciUserRoleListV1Response &a, TCciUserRoleListV1Response &b) {
  using ::std::swap;
  swap(a.responseDateTime, b.responseDateTime);
  swap(a.responseNonce, b.responseNonce);
  swap(a.resultMessage, b.resultMessage);
  swap(a.roleList, b.roleList);
  swap(a.__isset, b.__isset);
}

} // namespace
