/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cciUserListV1_constants.h"

namespace sudis {

const cciUserListV1Constants g_cciUserListV1_constants;

cciUserListV1Constants::cciUserListV1Constants() {
}

} // namespace

