/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef spsbExt_CONSTANTS_H
#define spsbExt_CONSTANTS_H

#include "spsbExt_types.h"

namespace spsb {

class spsbExtConstants {
 public:
  spsbExtConstants();

};

extern const spsbExtConstants g_spsbExt_constants;

} // namespace

#endif
