/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef spsbCommon_CONSTANTS_H
#define spsbCommon_CONSTANTS_H

#include "spsbCommon_types.h"

namespace spsb {

class spsbCommonConstants {
 public:
  spsbCommonConstants();

};

extern const spsbCommonConstants g_spsbCommon_constants;

} // namespace

#endif
