/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "spsbCommon_constants.h"

namespace spsb {

const spsbCommonConstants g_spsbCommon_constants;

spsbCommonConstants::spsbCommonConstants() {
}

} // namespace

