// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TCciUserLoginV1.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::sudis;

class TCciUserLoginV1Handler : virtual public TCciUserLoginV1If {
 public:
  TCciUserLoginV1Handler() {
    // Your initialization goes here
  }

  void cciUserLoginV1(TCciUserLoginV1Response& _return, const TCciUserLoginV1Request& request) {
    // Your implementation goes here
    printf("cciUserLoginV1\n");
  }

  void cciUserLoginV1Echo1(TCciUserLoginV1Request& _return, const TCciUserLoginV1Request& request) {
    // Your implementation goes here
    printf("cciUserLoginV1Echo1\n");
  }

  void cciUserLoginV1Echo2(TCciUserLoginV1Response& _return, const TCciUserLoginV1Response& response) {
    // Your implementation goes here
    printf("cciUserLoginV1Echo2\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TCciUserLoginV1Handler> handler(new TCciUserLoginV1Handler());
  shared_ptr<TProcessor> processor(new TCciUserLoginV1Processor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

