// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TCciUserLogoutV1.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::sudis;

class TCciUserLogoutV1Handler : virtual public TCciUserLogoutV1If {
 public:
  TCciUserLogoutV1Handler() {
    // Your initialization goes here
  }

  void cciUserLogoutV1(TCciUserLogoutV1Response& _return, const TCciUserLogoutV1Request& request) {
    // Your implementation goes here
    printf("cciUserLogoutV1\n");
  }

  void cciUserLogoutV1Echo1(TCciUserLogoutV1Request& _return, const TCciUserLogoutV1Request& request) {
    // Your implementation goes here
    printf("cciUserLogoutV1Echo1\n");
  }

  void cciUserLogoutV1Echo2(TCciUserLogoutV1Response& _return, const TCciUserLogoutV1Response& response) {
    // Your implementation goes here
    printf("cciUserLogoutV1Echo2\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TCciUserLogoutV1Handler> handler(new TCciUserLogoutV1Handler());
  shared_ptr<TProcessor> processor(new TCciUserLogoutV1Processor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

