/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TCciUserListV1_H
#define TCciUserListV1_H

#include <thrift/TDispatchProcessor.h>
#include "cciUserListV1_types.h"

namespace sudis {

class TCciUserListV1If {
 public:
  virtual ~TCciUserListV1If() {}
  virtual void cciUserListV1(TCciUserListV1Response& _return, const TCciUserListV1Request& request) = 0;
  virtual void cciUserListV1Echo1(TCciUserListV1Request& _return, const TCciUserListV1Request& request) = 0;
  virtual void cciUserListV1Echo2(TCciUserListV1Response& _return, const TCciUserListV1Response& response) = 0;
};

class TCciUserListV1IfFactory {
 public:
  typedef TCciUserListV1If Handler;

  virtual ~TCciUserListV1IfFactory() {}

  virtual TCciUserListV1If* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TCciUserListV1If* /* handler */) = 0;
};

class TCciUserListV1IfSingletonFactory : virtual public TCciUserListV1IfFactory {
 public:
  TCciUserListV1IfSingletonFactory(const boost::shared_ptr<TCciUserListV1If>& iface) : iface_(iface) {}
  virtual ~TCciUserListV1IfSingletonFactory() {}

  virtual TCciUserListV1If* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TCciUserListV1If* /* handler */) {}

 protected:
  boost::shared_ptr<TCciUserListV1If> iface_;
};

class TCciUserListV1Null : virtual public TCciUserListV1If {
 public:
  virtual ~TCciUserListV1Null() {}
  void cciUserListV1(TCciUserListV1Response& /* _return */, const TCciUserListV1Request& /* request */) {
    return;
  }
  void cciUserListV1Echo1(TCciUserListV1Request& /* _return */, const TCciUserListV1Request& /* request */) {
    return;
  }
  void cciUserListV1Echo2(TCciUserListV1Response& /* _return */, const TCciUserListV1Response& /* response */) {
    return;
  }
};

typedef struct _TCciUserListV1_cciUserListV1_args__isset {
  _TCciUserListV1_cciUserListV1_args__isset() : request(false) {}
  bool request;
} _TCciUserListV1_cciUserListV1_args__isset;

class TCciUserListV1_cciUserListV1_args {
 public:

  TCciUserListV1_cciUserListV1_args() {
  }

  virtual ~TCciUserListV1_cciUserListV1_args() throw() {}

  TCciUserListV1Request request;

  _TCciUserListV1_cciUserListV1_args__isset __isset;

  void __set_request(const TCciUserListV1Request& val) {
    request = val;
  }

  bool operator == (const TCciUserListV1_cciUserListV1_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const TCciUserListV1_cciUserListV1_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserListV1_cciUserListV1_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TCciUserListV1_cciUserListV1_pargs {
 public:


  virtual ~TCciUserListV1_cciUserListV1_pargs() throw() {}

  const TCciUserListV1Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserListV1_cciUserListV1_result__isset {
  _TCciUserListV1_cciUserListV1_result__isset() : success(false) {}
  bool success;
} _TCciUserListV1_cciUserListV1_result__isset;

class TCciUserListV1_cciUserListV1_result {
 public:

  TCciUserListV1_cciUserListV1_result() {
  }

  virtual ~TCciUserListV1_cciUserListV1_result() throw() {}

  TCciUserListV1Response success;

  _TCciUserListV1_cciUserListV1_result__isset __isset;

  void __set_success(const TCciUserListV1Response& val) {
    success = val;
  }

  bool operator == (const TCciUserListV1_cciUserListV1_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TCciUserListV1_cciUserListV1_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserListV1_cciUserListV1_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserListV1_cciUserListV1_presult__isset {
  _TCciUserListV1_cciUserListV1_presult__isset() : success(false) {}
  bool success;
} _TCciUserListV1_cciUserListV1_presult__isset;

class TCciUserListV1_cciUserListV1_presult {
 public:


  virtual ~TCciUserListV1_cciUserListV1_presult() throw() {}

  TCciUserListV1Response* success;

  _TCciUserListV1_cciUserListV1_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TCciUserListV1_cciUserListV1Echo1_args__isset {
  _TCciUserListV1_cciUserListV1Echo1_args__isset() : request(false) {}
  bool request;
} _TCciUserListV1_cciUserListV1Echo1_args__isset;

class TCciUserListV1_cciUserListV1Echo1_args {
 public:

  TCciUserListV1_cciUserListV1Echo1_args() {
  }

  virtual ~TCciUserListV1_cciUserListV1Echo1_args() throw() {}

  TCciUserListV1Request request;

  _TCciUserListV1_cciUserListV1Echo1_args__isset __isset;

  void __set_request(const TCciUserListV1Request& val) {
    request = val;
  }

  bool operator == (const TCciUserListV1_cciUserListV1Echo1_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const TCciUserListV1_cciUserListV1Echo1_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserListV1_cciUserListV1Echo1_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TCciUserListV1_cciUserListV1Echo1_pargs {
 public:


  virtual ~TCciUserListV1_cciUserListV1Echo1_pargs() throw() {}

  const TCciUserListV1Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserListV1_cciUserListV1Echo1_result__isset {
  _TCciUserListV1_cciUserListV1Echo1_result__isset() : success(false) {}
  bool success;
} _TCciUserListV1_cciUserListV1Echo1_result__isset;

class TCciUserListV1_cciUserListV1Echo1_result {
 public:

  TCciUserListV1_cciUserListV1Echo1_result() {
  }

  virtual ~TCciUserListV1_cciUserListV1Echo1_result() throw() {}

  TCciUserListV1Request success;

  _TCciUserListV1_cciUserListV1Echo1_result__isset __isset;

  void __set_success(const TCciUserListV1Request& val) {
    success = val;
  }

  bool operator == (const TCciUserListV1_cciUserListV1Echo1_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TCciUserListV1_cciUserListV1Echo1_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserListV1_cciUserListV1Echo1_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserListV1_cciUserListV1Echo1_presult__isset {
  _TCciUserListV1_cciUserListV1Echo1_presult__isset() : success(false) {}
  bool success;
} _TCciUserListV1_cciUserListV1Echo1_presult__isset;

class TCciUserListV1_cciUserListV1Echo1_presult {
 public:


  virtual ~TCciUserListV1_cciUserListV1Echo1_presult() throw() {}

  TCciUserListV1Request* success;

  _TCciUserListV1_cciUserListV1Echo1_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TCciUserListV1_cciUserListV1Echo2_args__isset {
  _TCciUserListV1_cciUserListV1Echo2_args__isset() : response(false) {}
  bool response;
} _TCciUserListV1_cciUserListV1Echo2_args__isset;

class TCciUserListV1_cciUserListV1Echo2_args {
 public:

  TCciUserListV1_cciUserListV1Echo2_args() {
  }

  virtual ~TCciUserListV1_cciUserListV1Echo2_args() throw() {}

  TCciUserListV1Response response;

  _TCciUserListV1_cciUserListV1Echo2_args__isset __isset;

  void __set_response(const TCciUserListV1Response& val) {
    response = val;
  }

  bool operator == (const TCciUserListV1_cciUserListV1Echo2_args & rhs) const
  {
    if (!(response == rhs.response))
      return false;
    return true;
  }
  bool operator != (const TCciUserListV1_cciUserListV1Echo2_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserListV1_cciUserListV1Echo2_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TCciUserListV1_cciUserListV1Echo2_pargs {
 public:


  virtual ~TCciUserListV1_cciUserListV1Echo2_pargs() throw() {}

  const TCciUserListV1Response* response;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserListV1_cciUserListV1Echo2_result__isset {
  _TCciUserListV1_cciUserListV1Echo2_result__isset() : success(false) {}
  bool success;
} _TCciUserListV1_cciUserListV1Echo2_result__isset;

class TCciUserListV1_cciUserListV1Echo2_result {
 public:

  TCciUserListV1_cciUserListV1Echo2_result() {
  }

  virtual ~TCciUserListV1_cciUserListV1Echo2_result() throw() {}

  TCciUserListV1Response success;

  _TCciUserListV1_cciUserListV1Echo2_result__isset __isset;

  void __set_success(const TCciUserListV1Response& val) {
    success = val;
  }

  bool operator == (const TCciUserListV1_cciUserListV1Echo2_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TCciUserListV1_cciUserListV1Echo2_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserListV1_cciUserListV1Echo2_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserListV1_cciUserListV1Echo2_presult__isset {
  _TCciUserListV1_cciUserListV1Echo2_presult__isset() : success(false) {}
  bool success;
} _TCciUserListV1_cciUserListV1Echo2_presult__isset;

class TCciUserListV1_cciUserListV1Echo2_presult {
 public:


  virtual ~TCciUserListV1_cciUserListV1Echo2_presult() throw() {}

  TCciUserListV1Response* success;

  _TCciUserListV1_cciUserListV1Echo2_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TCciUserListV1Client : virtual public TCciUserListV1If {
 public:
  TCciUserListV1Client(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  TCciUserListV1Client(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void cciUserListV1(TCciUserListV1Response& _return, const TCciUserListV1Request& request);
  void send_cciUserListV1(const TCciUserListV1Request& request);
  void recv_cciUserListV1(TCciUserListV1Response& _return);
  void cciUserListV1Echo1(TCciUserListV1Request& _return, const TCciUserListV1Request& request);
  void send_cciUserListV1Echo1(const TCciUserListV1Request& request);
  void recv_cciUserListV1Echo1(TCciUserListV1Request& _return);
  void cciUserListV1Echo2(TCciUserListV1Response& _return, const TCciUserListV1Response& response);
  void send_cciUserListV1Echo2(const TCciUserListV1Response& response);
  void recv_cciUserListV1Echo2(TCciUserListV1Response& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TCciUserListV1Processor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<TCciUserListV1If> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TCciUserListV1Processor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_cciUserListV1(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_cciUserListV1Echo1(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_cciUserListV1Echo2(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TCciUserListV1Processor(boost::shared_ptr<TCciUserListV1If> iface) :
    iface_(iface) {
    processMap_["cciUserListV1"] = &TCciUserListV1Processor::process_cciUserListV1;
    processMap_["cciUserListV1Echo1"] = &TCciUserListV1Processor::process_cciUserListV1Echo1;
    processMap_["cciUserListV1Echo2"] = &TCciUserListV1Processor::process_cciUserListV1Echo2;
  }

  virtual ~TCciUserListV1Processor() {}
};

class TCciUserListV1ProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TCciUserListV1ProcessorFactory(const ::boost::shared_ptr< TCciUserListV1IfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< TCciUserListV1IfFactory > handlerFactory_;
};

class TCciUserListV1Multiface : virtual public TCciUserListV1If {
 public:
  TCciUserListV1Multiface(std::vector<boost::shared_ptr<TCciUserListV1If> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TCciUserListV1Multiface() {}
 protected:
  std::vector<boost::shared_ptr<TCciUserListV1If> > ifaces_;
  TCciUserListV1Multiface() {}
  void add(boost::shared_ptr<TCciUserListV1If> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void cciUserListV1(TCciUserListV1Response& _return, const TCciUserListV1Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->cciUserListV1(_return, request);
    }
    ifaces_[i]->cciUserListV1(_return, request);
    return;
  }

  void cciUserListV1Echo1(TCciUserListV1Request& _return, const TCciUserListV1Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->cciUserListV1Echo1(_return, request);
    }
    ifaces_[i]->cciUserListV1Echo1(_return, request);
    return;
  }

  void cciUserListV1Echo2(TCciUserListV1Response& _return, const TCciUserListV1Response& response) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->cciUserListV1Echo2(_return, response);
    }
    ifaces_[i]->cciUserListV1Echo2(_return, response);
    return;
  }

};

} // namespace

#endif
