/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TCciUserRoleListV1_H
#define TCciUserRoleListV1_H

#include <thrift/TDispatchProcessor.h>
#include "cciUserRoleListV1_types.h"

namespace sudis {

class TCciUserRoleListV1If {
 public:
  virtual ~TCciUserRoleListV1If() {}
  virtual void cciUserRoleListV1(TCciUserRoleListV1Response& _return, const TCciUserRoleListV1Request& request) = 0;
  virtual void cciUserRoleListV1Echo1(TCciUserRoleListV1Request& _return, const TCciUserRoleListV1Request& request) = 0;
  virtual void cciUserRoleListV1Echo2(TCciUserRoleListV1Response& _return, const TCciUserRoleListV1Response& response) = 0;
};

class TCciUserRoleListV1IfFactory {
 public:
  typedef TCciUserRoleListV1If Handler;

  virtual ~TCciUserRoleListV1IfFactory() {}

  virtual TCciUserRoleListV1If* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TCciUserRoleListV1If* /* handler */) = 0;
};

class TCciUserRoleListV1IfSingletonFactory : virtual public TCciUserRoleListV1IfFactory {
 public:
  TCciUserRoleListV1IfSingletonFactory(const boost::shared_ptr<TCciUserRoleListV1If>& iface) : iface_(iface) {}
  virtual ~TCciUserRoleListV1IfSingletonFactory() {}

  virtual TCciUserRoleListV1If* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TCciUserRoleListV1If* /* handler */) {}

 protected:
  boost::shared_ptr<TCciUserRoleListV1If> iface_;
};

class TCciUserRoleListV1Null : virtual public TCciUserRoleListV1If {
 public:
  virtual ~TCciUserRoleListV1Null() {}
  void cciUserRoleListV1(TCciUserRoleListV1Response& /* _return */, const TCciUserRoleListV1Request& /* request */) {
    return;
  }
  void cciUserRoleListV1Echo1(TCciUserRoleListV1Request& /* _return */, const TCciUserRoleListV1Request& /* request */) {
    return;
  }
  void cciUserRoleListV1Echo2(TCciUserRoleListV1Response& /* _return */, const TCciUserRoleListV1Response& /* response */) {
    return;
  }
};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1_args__isset {
  _TCciUserRoleListV1_cciUserRoleListV1_args__isset() : request(false) {}
  bool request;
} _TCciUserRoleListV1_cciUserRoleListV1_args__isset;

class TCciUserRoleListV1_cciUserRoleListV1_args {
 public:

  TCciUserRoleListV1_cciUserRoleListV1_args() {
  }

  virtual ~TCciUserRoleListV1_cciUserRoleListV1_args() throw() {}

  TCciUserRoleListV1Request request;

  _TCciUserRoleListV1_cciUserRoleListV1_args__isset __isset;

  void __set_request(const TCciUserRoleListV1Request& val) {
    request = val;
  }

  bool operator == (const TCciUserRoleListV1_cciUserRoleListV1_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const TCciUserRoleListV1_cciUserRoleListV1_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserRoleListV1_cciUserRoleListV1_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TCciUserRoleListV1_cciUserRoleListV1_pargs {
 public:


  virtual ~TCciUserRoleListV1_cciUserRoleListV1_pargs() throw() {}

  const TCciUserRoleListV1Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1_result__isset {
  _TCciUserRoleListV1_cciUserRoleListV1_result__isset() : success(false) {}
  bool success;
} _TCciUserRoleListV1_cciUserRoleListV1_result__isset;

class TCciUserRoleListV1_cciUserRoleListV1_result {
 public:

  TCciUserRoleListV1_cciUserRoleListV1_result() {
  }

  virtual ~TCciUserRoleListV1_cciUserRoleListV1_result() throw() {}

  TCciUserRoleListV1Response success;

  _TCciUserRoleListV1_cciUserRoleListV1_result__isset __isset;

  void __set_success(const TCciUserRoleListV1Response& val) {
    success = val;
  }

  bool operator == (const TCciUserRoleListV1_cciUserRoleListV1_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TCciUserRoleListV1_cciUserRoleListV1_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserRoleListV1_cciUserRoleListV1_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1_presult__isset {
  _TCciUserRoleListV1_cciUserRoleListV1_presult__isset() : success(false) {}
  bool success;
} _TCciUserRoleListV1_cciUserRoleListV1_presult__isset;

class TCciUserRoleListV1_cciUserRoleListV1_presult {
 public:


  virtual ~TCciUserRoleListV1_cciUserRoleListV1_presult() throw() {}

  TCciUserRoleListV1Response* success;

  _TCciUserRoleListV1_cciUserRoleListV1_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1Echo1_args__isset {
  _TCciUserRoleListV1_cciUserRoleListV1Echo1_args__isset() : request(false) {}
  bool request;
} _TCciUserRoleListV1_cciUserRoleListV1Echo1_args__isset;

class TCciUserRoleListV1_cciUserRoleListV1Echo1_args {
 public:

  TCciUserRoleListV1_cciUserRoleListV1Echo1_args() {
  }

  virtual ~TCciUserRoleListV1_cciUserRoleListV1Echo1_args() throw() {}

  TCciUserRoleListV1Request request;

  _TCciUserRoleListV1_cciUserRoleListV1Echo1_args__isset __isset;

  void __set_request(const TCciUserRoleListV1Request& val) {
    request = val;
  }

  bool operator == (const TCciUserRoleListV1_cciUserRoleListV1Echo1_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const TCciUserRoleListV1_cciUserRoleListV1Echo1_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserRoleListV1_cciUserRoleListV1Echo1_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TCciUserRoleListV1_cciUserRoleListV1Echo1_pargs {
 public:


  virtual ~TCciUserRoleListV1_cciUserRoleListV1Echo1_pargs() throw() {}

  const TCciUserRoleListV1Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1Echo1_result__isset {
  _TCciUserRoleListV1_cciUserRoleListV1Echo1_result__isset() : success(false) {}
  bool success;
} _TCciUserRoleListV1_cciUserRoleListV1Echo1_result__isset;

class TCciUserRoleListV1_cciUserRoleListV1Echo1_result {
 public:

  TCciUserRoleListV1_cciUserRoleListV1Echo1_result() {
  }

  virtual ~TCciUserRoleListV1_cciUserRoleListV1Echo1_result() throw() {}

  TCciUserRoleListV1Request success;

  _TCciUserRoleListV1_cciUserRoleListV1Echo1_result__isset __isset;

  void __set_success(const TCciUserRoleListV1Request& val) {
    success = val;
  }

  bool operator == (const TCciUserRoleListV1_cciUserRoleListV1Echo1_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TCciUserRoleListV1_cciUserRoleListV1Echo1_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserRoleListV1_cciUserRoleListV1Echo1_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1Echo1_presult__isset {
  _TCciUserRoleListV1_cciUserRoleListV1Echo1_presult__isset() : success(false) {}
  bool success;
} _TCciUserRoleListV1_cciUserRoleListV1Echo1_presult__isset;

class TCciUserRoleListV1_cciUserRoleListV1Echo1_presult {
 public:


  virtual ~TCciUserRoleListV1_cciUserRoleListV1Echo1_presult() throw() {}

  TCciUserRoleListV1Request* success;

  _TCciUserRoleListV1_cciUserRoleListV1Echo1_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1Echo2_args__isset {
  _TCciUserRoleListV1_cciUserRoleListV1Echo2_args__isset() : response(false) {}
  bool response;
} _TCciUserRoleListV1_cciUserRoleListV1Echo2_args__isset;

class TCciUserRoleListV1_cciUserRoleListV1Echo2_args {
 public:

  TCciUserRoleListV1_cciUserRoleListV1Echo2_args() {
  }

  virtual ~TCciUserRoleListV1_cciUserRoleListV1Echo2_args() throw() {}

  TCciUserRoleListV1Response response;

  _TCciUserRoleListV1_cciUserRoleListV1Echo2_args__isset __isset;

  void __set_response(const TCciUserRoleListV1Response& val) {
    response = val;
  }

  bool operator == (const TCciUserRoleListV1_cciUserRoleListV1Echo2_args & rhs) const
  {
    if (!(response == rhs.response))
      return false;
    return true;
  }
  bool operator != (const TCciUserRoleListV1_cciUserRoleListV1Echo2_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserRoleListV1_cciUserRoleListV1Echo2_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TCciUserRoleListV1_cciUserRoleListV1Echo2_pargs {
 public:


  virtual ~TCciUserRoleListV1_cciUserRoleListV1Echo2_pargs() throw() {}

  const TCciUserRoleListV1Response* response;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1Echo2_result__isset {
  _TCciUserRoleListV1_cciUserRoleListV1Echo2_result__isset() : success(false) {}
  bool success;
} _TCciUserRoleListV1_cciUserRoleListV1Echo2_result__isset;

class TCciUserRoleListV1_cciUserRoleListV1Echo2_result {
 public:

  TCciUserRoleListV1_cciUserRoleListV1Echo2_result() {
  }

  virtual ~TCciUserRoleListV1_cciUserRoleListV1Echo2_result() throw() {}

  TCciUserRoleListV1Response success;

  _TCciUserRoleListV1_cciUserRoleListV1Echo2_result__isset __isset;

  void __set_success(const TCciUserRoleListV1Response& val) {
    success = val;
  }

  bool operator == (const TCciUserRoleListV1_cciUserRoleListV1Echo2_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TCciUserRoleListV1_cciUserRoleListV1Echo2_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TCciUserRoleListV1_cciUserRoleListV1Echo2_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TCciUserRoleListV1_cciUserRoleListV1Echo2_presult__isset {
  _TCciUserRoleListV1_cciUserRoleListV1Echo2_presult__isset() : success(false) {}
  bool success;
} _TCciUserRoleListV1_cciUserRoleListV1Echo2_presult__isset;

class TCciUserRoleListV1_cciUserRoleListV1Echo2_presult {
 public:


  virtual ~TCciUserRoleListV1_cciUserRoleListV1Echo2_presult() throw() {}

  TCciUserRoleListV1Response* success;

  _TCciUserRoleListV1_cciUserRoleListV1Echo2_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TCciUserRoleListV1Client : virtual public TCciUserRoleListV1If {
 public:
  TCciUserRoleListV1Client(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  TCciUserRoleListV1Client(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void cciUserRoleListV1(TCciUserRoleListV1Response& _return, const TCciUserRoleListV1Request& request);
  void send_cciUserRoleListV1(const TCciUserRoleListV1Request& request);
  void recv_cciUserRoleListV1(TCciUserRoleListV1Response& _return);
  void cciUserRoleListV1Echo1(TCciUserRoleListV1Request& _return, const TCciUserRoleListV1Request& request);
  void send_cciUserRoleListV1Echo1(const TCciUserRoleListV1Request& request);
  void recv_cciUserRoleListV1Echo1(TCciUserRoleListV1Request& _return);
  void cciUserRoleListV1Echo2(TCciUserRoleListV1Response& _return, const TCciUserRoleListV1Response& response);
  void send_cciUserRoleListV1Echo2(const TCciUserRoleListV1Response& response);
  void recv_cciUserRoleListV1Echo2(TCciUserRoleListV1Response& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TCciUserRoleListV1Processor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<TCciUserRoleListV1If> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TCciUserRoleListV1Processor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_cciUserRoleListV1(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_cciUserRoleListV1Echo1(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_cciUserRoleListV1Echo2(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TCciUserRoleListV1Processor(boost::shared_ptr<TCciUserRoleListV1If> iface) :
    iface_(iface) {
    processMap_["cciUserRoleListV1"] = &TCciUserRoleListV1Processor::process_cciUserRoleListV1;
    processMap_["cciUserRoleListV1Echo1"] = &TCciUserRoleListV1Processor::process_cciUserRoleListV1Echo1;
    processMap_["cciUserRoleListV1Echo2"] = &TCciUserRoleListV1Processor::process_cciUserRoleListV1Echo2;
  }

  virtual ~TCciUserRoleListV1Processor() {}
};

class TCciUserRoleListV1ProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TCciUserRoleListV1ProcessorFactory(const ::boost::shared_ptr< TCciUserRoleListV1IfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< TCciUserRoleListV1IfFactory > handlerFactory_;
};

class TCciUserRoleListV1Multiface : virtual public TCciUserRoleListV1If {
 public:
  TCciUserRoleListV1Multiface(std::vector<boost::shared_ptr<TCciUserRoleListV1If> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TCciUserRoleListV1Multiface() {}
 protected:
  std::vector<boost::shared_ptr<TCciUserRoleListV1If> > ifaces_;
  TCciUserRoleListV1Multiface() {}
  void add(boost::shared_ptr<TCciUserRoleListV1If> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void cciUserRoleListV1(TCciUserRoleListV1Response& _return, const TCciUserRoleListV1Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->cciUserRoleListV1(_return, request);
    }
    ifaces_[i]->cciUserRoleListV1(_return, request);
    return;
  }

  void cciUserRoleListV1Echo1(TCciUserRoleListV1Request& _return, const TCciUserRoleListV1Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->cciUserRoleListV1Echo1(_return, request);
    }
    ifaces_[i]->cciUserRoleListV1Echo1(_return, request);
    return;
  }

  void cciUserRoleListV1Echo2(TCciUserRoleListV1Response& _return, const TCciUserRoleListV1Response& response) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->cciUserRoleListV1Echo2(_return, response);
    }
    ifaces_[i]->cciUserRoleListV1Echo2(_return, response);
    return;
  }

};

} // namespace

#endif
