// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TCciUserListV1.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::sudis;

class TCciUserListV1Handler : virtual public TCciUserListV1If {
 public:
  TCciUserListV1Handler() {
    // Your initialization goes here
  }

  void cciUserListV1(TCciUserListV1Response& _return, const TCciUserListV1Request& request) {
    // Your implementation goes here
    printf("cciUserListV1\n");
  }

  void cciUserListV1Echo1(TCciUserListV1Request& _return, const TCciUserListV1Request& request) {
    // Your implementation goes here
    printf("cciUserListV1Echo1\n");
  }

  void cciUserListV1Echo2(TCciUserListV1Response& _return, const TCciUserListV1Response& response) {
    // Your implementation goes here
    printf("cciUserListV1Echo2\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TCciUserListV1Handler> handler(new TCciUserListV1Handler());
  shared_ptr<TProcessor> processor(new TCciUserListV1Processor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

