// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TCciUserRoleListV1.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::sudis;

class TCciUserRoleListV1Handler : virtual public TCciUserRoleListV1If {
 public:
  TCciUserRoleListV1Handler() {
    // Your initialization goes here
  }

  void cciUserRoleListV1(TCciUserRoleListV1Response& _return, const TCciUserRoleListV1Request& request) {
    // Your implementation goes here
    printf("cciUserRoleListV1\n");
  }

  void cciUserRoleListV1Echo1(TCciUserRoleListV1Request& _return, const TCciUserRoleListV1Request& request) {
    // Your implementation goes here
    printf("cciUserRoleListV1Echo1\n");
  }

  void cciUserRoleListV1Echo2(TCciUserRoleListV1Response& _return, const TCciUserRoleListV1Response& response) {
    // Your implementation goes here
    printf("cciUserRoleListV1Echo2\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TCciUserRoleListV1Handler> handler(new TCciUserRoleListV1Handler());
  shared_ptr<TProcessor> processor(new TCciUserRoleListV1Processor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

