/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ticketV3_constants.h"



const ticketV3Constants g_ticketV3_constants;

ticketV3Constants::ticketV3Constants() {
}



