/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ticketV3_CONSTANTS_H
#define ticketV3_CONSTANTS_H

#include "ticketV3_types.h"



class ticketV3Constants {
 public:
  ticketV3Constants();

};

extern const ticketV3Constants g_ticketV3_constants;



#endif
