// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TServiceExtSpsb.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::spsb;

class TServiceExtSpsbHandler : virtual public TServiceExtSpsbIf {
 public:
  TServiceExtSpsbHandler() {
    // Your initialization goes here
  }

  void ping(TSpsbPingResult& _return, const TSpsbPingArgs& arguments) {
    // Your implementation goes here
    printf("ping\n");
  }

  void logEvent(TSpsbLogEventResult& _return, const TSpsbLogEventArgs& arguments) {
    // Your implementation goes here
    printf("logEvent\n");
  }

  void listEvents(TSpsbListEventsResult& _return, const TSpsbListEventsArgs& arguments) {
    // Your implementation goes here
    printf("listEvents\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TServiceExtSpsbHandler> handler(new TServiceExtSpsbHandler());
  shared_ptr<TProcessor> processor(new TServiceExtSpsbProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

