/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef UserLoginV3_H
#define UserLoginV3_H

#include <thrift/TDispatchProcessor.h>
#include "cciUserLoginV3_types.h"



class UserLoginV3If {
 public:
  virtual ~UserLoginV3If() {}
  virtual void userLoginV3(UserLoginV3Response& _return, const UserLoginV3Request& request) = 0;
};

class UserLoginV3IfFactory {
 public:
  typedef UserLoginV3If Handler;

  virtual ~UserLoginV3IfFactory() {}

  virtual UserLoginV3If* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(UserLoginV3If* /* handler */) = 0;
};

class UserLoginV3IfSingletonFactory : virtual public UserLoginV3IfFactory {
 public:
  UserLoginV3IfSingletonFactory(const boost::shared_ptr<UserLoginV3If>& iface) : iface_(iface) {}
  virtual ~UserLoginV3IfSingletonFactory() {}

  virtual UserLoginV3If* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(UserLoginV3If* /* handler */) {}

 protected:
  boost::shared_ptr<UserLoginV3If> iface_;
};

class UserLoginV3Null : virtual public UserLoginV3If {
 public:
  virtual ~UserLoginV3Null() {}
  void userLoginV3(UserLoginV3Response& /* _return */, const UserLoginV3Request& /* request */) {
    return;
  }
};

typedef struct _UserLoginV3_userLoginV3_args__isset {
  _UserLoginV3_userLoginV3_args__isset() : request(false) {}
  bool request;
} _UserLoginV3_userLoginV3_args__isset;

class UserLoginV3_userLoginV3_args {
 public:

  UserLoginV3_userLoginV3_args() {
  }

  virtual ~UserLoginV3_userLoginV3_args() throw() {}

  UserLoginV3Request request;

  _UserLoginV3_userLoginV3_args__isset __isset;

  void __set_request(const UserLoginV3Request& val) {
    request = val;
  }

  bool operator == (const UserLoginV3_userLoginV3_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const UserLoginV3_userLoginV3_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UserLoginV3_userLoginV3_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class UserLoginV3_userLoginV3_pargs {
 public:


  virtual ~UserLoginV3_userLoginV3_pargs() throw() {}

  const UserLoginV3Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UserLoginV3_userLoginV3_result__isset {
  _UserLoginV3_userLoginV3_result__isset() : success(false) {}
  bool success;
} _UserLoginV3_userLoginV3_result__isset;

class UserLoginV3_userLoginV3_result {
 public:

  UserLoginV3_userLoginV3_result() {
  }

  virtual ~UserLoginV3_userLoginV3_result() throw() {}

  UserLoginV3Response success;

  _UserLoginV3_userLoginV3_result__isset __isset;

  void __set_success(const UserLoginV3Response& val) {
    success = val;
  }

  bool operator == (const UserLoginV3_userLoginV3_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const UserLoginV3_userLoginV3_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UserLoginV3_userLoginV3_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UserLoginV3_userLoginV3_presult__isset {
  _UserLoginV3_userLoginV3_presult__isset() : success(false) {}
  bool success;
} _UserLoginV3_userLoginV3_presult__isset;

class UserLoginV3_userLoginV3_presult {
 public:


  virtual ~UserLoginV3_userLoginV3_presult() throw() {}

  UserLoginV3Response* success;

  _UserLoginV3_userLoginV3_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class UserLoginV3Client : virtual public UserLoginV3If {
 public:
  UserLoginV3Client(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  UserLoginV3Client(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void userLoginV3(UserLoginV3Response& _return, const UserLoginV3Request& request);
  void send_userLoginV3(const UserLoginV3Request& request);
  void recv_userLoginV3(UserLoginV3Response& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class UserLoginV3Processor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<UserLoginV3If> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (UserLoginV3Processor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_userLoginV3(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  UserLoginV3Processor(boost::shared_ptr<UserLoginV3If> iface) :
    iface_(iface) {
    processMap_["userLoginV3"] = &UserLoginV3Processor::process_userLoginV3;
  }

  virtual ~UserLoginV3Processor() {}
};

class UserLoginV3ProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  UserLoginV3ProcessorFactory(const ::boost::shared_ptr< UserLoginV3IfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< UserLoginV3IfFactory > handlerFactory_;
};

class UserLoginV3Multiface : virtual public UserLoginV3If {
 public:
  UserLoginV3Multiface(std::vector<boost::shared_ptr<UserLoginV3If> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~UserLoginV3Multiface() {}
 protected:
  std::vector<boost::shared_ptr<UserLoginV3If> > ifaces_;
  UserLoginV3Multiface() {}
  void add(boost::shared_ptr<UserLoginV3If> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void userLoginV3(UserLoginV3Response& _return, const UserLoginV3Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->userLoginV3(_return, request);
    }
    ifaces_[i]->userLoginV3(_return, request);
    return;
  }

};



#endif
